model:
  best_model: GradientBoosting
  feature_sets:
    rfe:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '9'
    - '11'
    - '14'
    rfe_method: RandomForestRegressor
    selected_features_count: 10
    total_features: 16
  mae: 9337.728948203796
  name: house_price_model
  parameters:
    alpha: 0.9
    ccp_alpha: 0.0
    criterion: friedman_mse
    init: null
    learning_rate: 0.1
    loss: squared_error
    max_depth: 3
    max_features: null
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    min_samples_leaf: 1
    min_samples_split: 2
    min_weight_fraction_leaf: 0.0
    n_estimators: 150
    n_iter_no_change: null
    random_state: null
    subsample: 0.8
    tol: 0.0001
    validation_fraction: 0.1
    verbose: 0
    warm_start: false
  r2_score: 0.9964564960844177
  target_variable: price
